### PR TITLE
Better PWA

### PR DESCRIPTION
**Pull request by DivadNojnarg**
Include pwacompat from google to automate the creation of splash screen, touch icon, ...

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
Hi @JohnCoene and @pvictor 

could you try: https://dgranjon.shinyapps.io/miniUI2DemoTest/

Save it to your home screen and let me know if:
- you see the start screen when you launch the app from your apps menu (You should)
- If yes, is it white with a small icon at the center?
- Do you see a white bar at the bottom of the app? (You should not ;))

**Comment by JohnCoene** [comment]
Yes I see exactly that with the white bar and all. looking nice!

**Comment by DivadNojnarg** [comment]
Thanks @JohnCoene ! I will extend to the community to capture more devices. Your app will benefit from that new feature though ;)

**Comment by pvictor** [comment]
Works great! 👍 (android + chrome)

**Comment by DivadNojnarg** [comment]
According to some reports, splash screens don’t render on the new iOS release (13.3.1). BTW, this is a game changer for most of platforms.

**Pull request merged**
