### PR TITLE
added getDefaultReactiveDomain for session args

### PR DESCRIPTION
**Pull request by pvictor**
Hi David,

Small changes to add `session = shiny::getDefaultReactiveDomain()` everywhere it's possible.

Victor

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
Cool! This will prevent to have session= session all the time.

**Comment by pvictor** [comment]
Yeah, I think it's too late for inputs, too bad...

**Comment by DivadNojnarg** [comment]
Why?

**Comment by pvictor** [comment]
Ideally we would transform 

```
updateInput(session, inputId, newVal)
```
in 
```
updateinput(inputId, newVal, session = shiny::getDefaultReactiveDomain())
```
that would be a breaking change for people doing

```
updateInput(session, "ID", "value")
```
without using named arguments.

But since there has been only one release on CRAN maybe it can be acceptable, it would make things easier in the future for new users.

**Comment by DivadNojnarg** [comment]
I agree. Only one release, we can justify it is for the best! Go ahead ;)

**Comment by pvictor** [comment]
Done, modified all update methods, updated documentation and added a note in NEWS

**Pull request merged**
