### PR TITLE
New datePickerInput method

### PR DESCRIPTION
**Pull request by pvictor**
Hello David,

This is to discuss some changes in `f7DatePicker`. What I've done : 
* updated the way you pass option to JS method `app.calendar.create` : replaced data attributes by config JSON
* Updated the JS `getValue` to return selected date
* Added R `.onLoad` to add a custom `registerInputHandler` to deal with objects return by `f7DatePickerBinding`

Caution, this introduce a possible breaking change, now the input value returned by `f7DatePicker` is a `Date` no more a `character`.

Let me know what do you think

Victor

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
> Caution, this introduces a possible breaking change, now the input value returned by f7DatePicker is a Date no more a character.

This is what shiny does, and it should have been like this. Thanks!

How would you solve the updateF7DatePicker issue assuming that for some reasons, `app.calendar.get` returns undefined?

**Comment by pvictor** [comment]
Update selected value is easy, will implement it.
Update all other options, I don't know, maybe it will need to destroy et re-create the instance...

**Comment by pvictor** [comment]
Ok, now : 

```r
updateF7DatePicker(
  session,
  inputId = "mypicker",
  value = Sys.Date()
)
```

works.

And it should be possible to select multiple dates.

**Comment by DivadNojnarg** [comment]
Thanks!. The main interest of app.calendar.get was to seamlessly access all picker params and update them.

**Comment by pvictor** [comment]
Okay, now you can update **any** parameters with `updateF7DatePicker`()`.
I also added `multiple` argument to `f7DatePicker()` to select multiple dates.
And remake example.

Should work!

**Comment by DivadNojnarg** [comment]
Thanks Victor , I will merge once checked 👍

**Pull request merged**
