### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by dmenne**
- Corrected handling of deprecated functions, no more deprecation warnings for the correct functions.
 - Using the following for deprecated functions
```
#' @inheritParams  xxxx
#' @rdname f7-deprecated
#' @keywords internal
```

- Deprecated functions are marked with `@keyword internal`, so help still accessible via `?f7InsertTab` etc, but do not longer turn up in the list of functions.

- In Englisch, using "a" vs. "an" is based on phonetical rules only. Since eff/7 starts with a vowel, it should be "hides __an__ \link{f7Navbar}" and the likes

- Added Dieter Menne as a ctb to DESCRIPTION, and used version number 9001.

This is an intermediate version doing a first step. I will later post suggestions for the help and test system on in the issues.

### CODE REVIEW

**Comment by dmenne** [comment]
Corrected issue 174.

**Comment by DivadNojnarg** [comment]
Thanks for this WIP. I pushed a fix to the broken reactivity in #174 . Don't worry about the conflicts, I'll fix them later.

**Comment by dmenne** [comment]
How to resolve this? Your versions gives the wrong label "tabx_"

**Comment by DivadNojnarg** [comment]
@dmenne : why did you close this PR?

**Comment by dmenne** [comment]
Sorry, I first thought that this was a no-issue. Thanks for merging it now.

**Comment by DivadNojnarg** [comment]
I'm reopening

**Comment by DivadNojnarg** [comment]
Thanks for all of this ;)

**Pull request merged**
